### ISSUE TITLE
[REQUEST] Persistent Session

### ISSUE THREAD

**Issue by SgtRaider** [hawgview/hawgview-public#3]
**What service are you suggesting a feature fore? (Delete services not applicable)**
Hawg View | CAS Planner

**Is your feature request related to a problem? Please describe.**

Due to some error like the Bullseye one I reported, it would be awesome a persistent Session in order to not lose all while planning. 

In adition, if in the future a Log In, and persistent Session is added, it would be great to plot, targets, threats, updates... while other people in the Session logged can observe those changes in live.

**Describe the solution you'd like**
The solution I would like is to implement a Register and Log In, in order to have persistent data in the web, maybe its not necessary to upload all the Session data, only the shapes, and routes created in the last session. In adition, it would be a good feature after implementing the Session, allow different people to Log In that Session in order to monitor live changes in the scenario (Changed by someone logged in the Session) while performing a training.

**Describe alternatives you've considered**

**Additional context**

**Comment by chris-m92** [comment]
Great feature request, I'm working to get the infrastructure to introduce this to make saving / sharing scenarios much easier, live updating (like Google Docs), as well as using Local Storage to save session on your client for if that stuff happens, or you just close and return, it persists with the information that you were working on.

**Comment by chris-m92** [comment]
Local storage added in version `4.114.1`. Users can now accept or reject (and subsequently grant/revoke) cookies for use with Hawg View. Actions will result in a persistent state in Local Storage which is used when loading the page (if exists).

Standby for more regarding "live" editing.
